# Generated by Django 4.0.5 on 2022-07-04 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zeus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comidas',
            name='precio',
            field=models.FloatField(),
        ),
    ]
